version: '3'
 
services:
  fastapi:
    image: 975049969539.dkr.ecr.ap-south-1.amazonaws.com/fastapi:1.0.0
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql
      - mongo
      - redis
 
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fasapi
    volumes:
      - mysql_data:/var/lib/mysql
 
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
 
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
 
volumes:
  mysql_data:
  mongo_data: